package com.campusfixai.controller;

import com.campusfixai.model.*; import com.campusfixai.repo.*; import com.campusfixai.service.AgentOrchestrator; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.LocalDateTime; import java.util.*;

@RestController @RequestMapping("/api")
public class CampusFixController {
  private final IncidentRepository incidents; private final ReportRepository reports; private final ProfessionalRepository professionals; private final AgentLogRepository logs; private final AgentOrchestrator orchestrator;
  public CampusFixController(IncidentRepository i,ReportRepository r,ProfessionalRepository p,AgentLogRepository l,AgentOrchestrator o){incidents=i;reports=r;professionals=p;logs=l;orchestrator=o;}
  @GetMapping("/health") public Map<String,Object> health(){return Map.of("status","UP","service","CampusFix AI","time",LocalDateTime.now());}
  @GetMapping("/professionals") public List<Professional> professionals(){return professionals.findAll();}
  @GetMapping("/incidents") public List<Map<String,Object>> incidents(){return incidents.findTop50ByOrderByCreatedAtDesc().stream().map(this::summary).toList();}
  @GetMapping("/incidents/{id}") public ResponseEntity<?> incident(@PathVariable Long id){return incidents.findById(id).<ResponseEntity<?>>map(i->ResponseEntity.ok(detail(i))).orElseGet(()->ResponseEntity.notFound().build());}
  @PostMapping("/reports") public ResponseEntity<?> report(@Valid @RequestBody ApiDtos.ReportRequest x){Report r=new Report();r.setVtuNo(x.vtuNo());r.setStudentName(x.studentName());r.setAreaType(x.areaType());r.setHostel(x.hostel());r.setHostelBlock(x.hostelBlock());r.setFloor(x.floor());r.setRoomNo(x.roomNo());r.setUniversityBlock(x.universityBlock());r.setForum(x.forum());r.setProblem(x.problem()); Incident i=orchestrator.process(r); return ResponseEntity.ok(Map.of("incident",detail(i)));}
  @PatchMapping("/incidents/{id}") public ResponseEntity<?> update(@PathVariable Long id,@RequestBody ApiDtos.StatusRequest x){return incidents.findById(id).map(i->{i.setStatus(x.status());i.setVerified(Boolean.TRUE.equals(x.verified()));i.setUpdatedAt(LocalDateTime.now());incidents.save(i);return ResponseEntity.ok(detail(i));}).orElseGet(()->ResponseEntity.notFound().build());}
  private Map<String,Object> summary(Incident i){Map<String,Object> m=new LinkedHashMap<>();m.put("id",i.getId());m.put("code",i.getCode());m.put("areaType",i.getAreaType());m.put("hostel",n(i.getHostel()));m.put("hostelBlock",n(i.getHostelBlock()));m.put("universityBlock",n(i.getUniversityBlock()));m.put("forum",i.getForum());m.put("problem",i.getProblem());m.put("category",i.getCategory());m.put("priority",i.getPriority());m.put("status",i.getStatus());m.put("linkedReports",i.getLinkedReports());return m;}
  private Map<String,Object> detail(Incident i){var p=i.getProfessional(); Map<String,Object> m=new LinkedHashMap<>(); m.put("id",i.getId()); m.put("code",i.getCode()); m.put("areaType",i.getAreaType()); m.put("hostel",n(i.getHostel())); m.put("hostelBlock",n(i.getHostelBlock())); m.put("floor",n(i.getFloor())); m.put("roomNo",n(i.getRoomNo())); m.put("universityBlock",n(i.getUniversityBlock())); m.put("forum",i.getForum()); m.put("problem",i.getProblem()); m.put("category",i.getCategory()); m.put("priority",i.getPriority()); m.put("status",i.getStatus()); m.put("rootCause",n(i.getRootCause())); m.put("requiredSpecialization",i.getRequiredSpecialization()); m.put("professional",p==null?null:Map.of("id",p.getId(),"name",p.getName(),"department",p.getDepartment(),"specialization",p.getSpecialization())); m.put("linkedReports",i.getLinkedReports()); m.put("plan",n(i.getPlan())); m.put("verified",i.isVerified()); m.put("logs",logs.findByIncidentIdOrderByCreatedAtAsc(i.getId())); return m;}
  private String n(String s){return s==null?"":s;}
}
